### ISSUE TITLE
Don't close standard i/o streams?

### ISSUE THREAD

**Issue by eush77** [mafintosh/multi-write-stream#1]
Attempt of closing stdout or stderr in Node throws an exception. Maybe check for `process.stdout` or `process.stderr` and skip the `.end` part?

For example, this minimal tee-like program does not work:

``` js
var multiWriteStream = require('multi-write-stream');
var fs = require('fs');

process.stdin.pipe(multiWriteStream([
  process.stdout,
  fs.createWriteStream(process.argv[2])
]));
```

```
$ echo hello |node tee file.txt
hello
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: process.stdout cannot be closed.
```

You can `.pipe(process.stdout)` with no problems, so it's at least intuitive to expect `.pipe(multiWriteStream([process.stdout, ...]))` to work.

**Comment by mafintosh** [comment]
Good idea. Send me a pr for this :)

**Comment by ziggythehamster** [comment]
I've seen some libraries control this with `{ end: false }` as an option. There are other cases besides stdout/stderr where you might want to pipe but leave the files un-ended
